{% set name = "kissim" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/volkamerlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: b0ab08ce659cdc9afcbf2e846fdf93d6420aea95233b9905b2ad379558b66c97

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kissim = kissim.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - numpy
    - pandas
    - scipy
    - matplotlib-base
    - jupyter
    - jupyterlab
    - ipywidgets
    - nglview
    - biopython <=1.77
    - opencadd

test:
  requires:
    - python {{ python_min }}
  imports:
    - kissim
  commands:
    - kissim -h

about:
  home: https://github.com/volkamerlab/kissim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Subpocket-based fingerprint for kinase pocket comparison
  description: |
    Subpocket-based fingerprint for kinase pocket comparison
  doc_url: https://kissim.readthedocs.io/
  dev_url: https://github.com/volkamerlab/kissim

extra:
  recipe-maintainers:
    - dominiquesydow
    - AndreaVolkamer
